# Generated by Django 3.1.5 on 2021-01-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=15)),
            ],
        ),
    ]
