# Generated by Django 3.1.5 on 2021-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'verbose_name': 'Rider', 'verbose_name_plural': 'Riders'},
        ),
        migrations.AddField(
            model_name='rider',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
