# Generated by Django 3.1.5 on 2021-01-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20210128_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='slug',
        ),
    ]
