# Generated by Django 3.1.5 on 2021-02-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_auto_20210129_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.EmailField(default='hello@mail.com', max_length=15),
            preserve_default=False,
        ),
    ]
