# Generated by Django 3.1.5 on 2021-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_rider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
