# Generated by Django 3.1.5 on 2021-02-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_auto_20210129_1310'),
        ('order', '0002_auto_20210210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider.rider'),
        ),
    ]
