# Generated by Django 3.1.5 on 2021-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210210_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider_assigned_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
